### ISSUE TITLE
Upload to AWS

### ISSUE THREAD

**Issue by migueljrodrigues** [ysfmag/aws-lambda-py-pandas-template#1]
Hi @ysfmag,

Can you successfully run this on AWS Lambda environment? I can also run a snippet locally, but when I try to run it in AWS, it gives me the message:

**"errorMessage": "Unable to import module..."**

**Comment by ymaghzaz** [comment]
Hi @migueljrodrigues 

When you build , a directory called .aws-sam will be created , inside this directory you will have /build/MyFunction.
so you need to be in  in  : .aws-sam/build/MyFunction
and zip your file, and upload the ziped file to s3  , after that create a function lambda and use the s3 url  of uploded file  as source code .
good luck

**Comment by migueljrodrigues** [comment]
Hey @ysfmag, 

Thanks for the quick reply. It worked 👍 . Also, using the **sam package** command also worked, and it spared me the work you described.

Thanks!
